jobs:
  include:
    - os: linux
      sudo: required
      language: python
      python: 3.6
      dist: xenial
      # command to install Git LFS
      before_install:
      - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
      - python --version
      - pip install -U pip
      - pip install -U pytest
      # command to install dependencies
      install: 
      - "pip install -r requirements.txt"
      before_script:
      - git lfs pull
      # command to run tests
      script: python ./tests/test_objects/test_waveclass/test.py
      script: python ./tests/test_objects/test_bodyclass/test.py
    - os: osx
      osx_image: xcode10
      language: generic
      env: PYTHON=36
      # command to install Git LFS
      before_install:
      - brew install git-lfs
      # underneath methods from http://www.pyslvs.com/blog/yuan_2018-09-22.html
      - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew install swig;
        curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci;
        source ./macports-ci install;
        fi
      - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        yes | sudo port install python$PYTHON;
        yes | sudo port install py$PYTHON-pip;
        sudo port select --set python3 python$PYTHON;
        sudo port select --set pip pip$PYTHON;
        pip install pyinstaller --user;
        export PATH=$PATH:/Users/travis/Library/Python/$PYTHON/bin;
        fi
      - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        python3 --version;
        pip --version;
        pyinstaller --version;
        fi
      # command to install dependencies
      install: 
      - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        pip install -r requirements.txt --user;
        fi
      #- "pip install -r requirements.txt"
      before_script:
      - git lfs pull
      # command to run tests
      script: python ./tests/test_objects/test_waveclass/test.py
      script: python ./tests/test_objects/test_bodyclass/test.py
