language: python
python:  "3.6.10"
# comman to install Git LFS
before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
- git lfs pull
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: pytest
