jobs:
  include:
    - os: linux
      sudo: required
      language: python
      python: 3.6
      dist: xenial
      # command to install Git LFS
      before_install:
      - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
      - python --version
      - pip install -U pip
      - pip install -U pytest
      # command to install dependencies
      install: 
      - "pip install -r requirements.txt"
      before_script:
      - git lfs pull
      # command to run tests
      script: python ./tests/test_objects/test_waveclass/test.py
      script: python ./tests/test_objects/test_bodyclass/test.py
    - os: osx
      osx_image: xcode10
      language: generic
      env: PYTHON=36
      # command to install Git LFS
      before_install:
      - brew install git-lfs
      - python3 --version
      - pip install -U pip
      - pip install -U pytest
      # command to install dependencies
      install: 
      - "pip install -r requirements.txt"
      before_script:
      - git lfs pull
      # command to run tests
      script: python3 ./tests/test_objects/test_waveclass/test.py
      script: python3 ./tests/test_objects/test_bodyclass/test.py
